### Installer REST Client et créez des requêtes HTTP en mettant le type (GET POST PUT PATCH DELETE) avec l'URL de l'api / routes

# GET http://localhost:3000/users

###

POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "firstname": "DELAHAYE",
    "lastname": "Gabriel",
    "email": "gabriel",
    "google_id": "1234"
}

